---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.application }}
  labels:
    name: {{ .Values.namespace.application }}
    environment: {{ .Values.global.environment }}
    project: {{ .Values.global.projectName }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.monitoring }}
  labels:
    name: {{ .Values.namespace.monitoring }}
    environment: {{ .Values.global.environment }}
    project: {{ .Values.global.projectName }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.production }}
  labels:
    name: {{ .Values.namespace.production }}
    environment: {{ .Values.global.environment }}
    project: {{ .Values.global.projectName }}
